#!/usr/bin/env python3
"""Generate a production-style iOS folder scaffold from a blueprint.

Usage:
  python agentic-ios/tools/generate_ios_scaffold.py --app-name TaskManager --output ./generated
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import textwrap


def load_blueprint(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def touch_file(path: Path, content: str = "") -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def swift_stub(file_path: str) -> str:
    name = Path(file_path).stem
    if name.endswith("View"):
        return textwrap.dedent(
            f"""\
            import SwiftUI

            struct {name}: View {{
                var body: some View {{
                    Text(\"{name}\")
                }}
            }}
            """
        )
    if name.endswith("ViewModel"):
        return textwrap.dedent(
            f"""\
            import Foundation

            @MainActor
            final class {name}: ObservableObject {{
                @Published var isLoading = false
                @Published var errorMessage: String?
            }}
            """
        )
    return f"// {name}\n"


def create_scaffold(blueprint: dict, app_name: str, output: Path) -> Path:
    root = output / app_name
    root.mkdir(parents=True, exist_ok=True)

    for folder in blueprint.get("folders", []):
        (root / folder).mkdir(exist_ok=True)

    for key in ["core_files", "shared_files", "model_files"]:
        for rel in blueprint.get(key, []):
            content = swift_stub(rel) if rel.endswith(".swift") else ""
            touch_file(root / rel, content)

    for feature in blueprint.get("features", []):
        for rel in feature.get("files", []):
            touch_file(root / rel, swift_stub(rel))

    readme = root / "README.md"
    readme.write_text(
        textwrap.dedent(
            f"""\
            # {app_name}

            Generated by Agentic iOS scaffold generator.

            ## Stack
            - Swift + SwiftUI
            - MVVM
            - iOS {blueprint.get('app', {}).get('min_ios', '17.0')}+

            ## Included quality gates
            """
        )
        + "\n".join(f"- {gate}" for gate in blueprint.get("quality_gates", []))
        + "\n",
        encoding="utf-8",
    )

    return root


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate an iOS scaffold")
    parser.add_argument("--app-name", required=True, help="App folder name")
    parser.add_argument(
        "--blueprint",
        default="agentic-ios/templates/project_blueprint.json",
        help="Path to JSON blueprint",
    )
    parser.add_argument("--output", default=".", help="Output parent directory")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    blueprint = load_blueprint(Path(args.blueprint))
    output_path = create_scaffold(blueprint, args.app_name, Path(args.output))
    print(f"Scaffold created at: {output_path}")


if __name__ == "__main__":
    main()
